### ISSUE TITLE
mysqlとの接続エラー

### ISSUE THREAD

**Issue by suaaa7** [suaaa7/scala_webapp#12]
```
Cannot connect to database [default]

In /opt/scala/mojipic/target/scala-2.12/classes/application.conf:11
7play.filters.headers.contentSecurityPolicy = null
8
9# JDBC settings
10db.default.driver="com.mysql.jdbc.Driver"
11db.default.url="jdbc:mysql://192.168.99.100:3306/mojipic"
12db.default.username="root"
13db.default.password="mysql"
14
15# Connection Pool settings
```

**Comment by suaaa7** [comment]
`docker-compose up -d`でStateがrestartingになっている
`restart: always`を外すとExit 1になる

**Comment by suaaa7** [comment]
`docker-compose logs | grep mysql`

```
mojipic-mysql   | Initializing database
mojipic-mysql   | 2019-03-16T18:15:45.222310Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mojipic-mysql   | 2019-03-16T18:15:45.238126Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
mojipic-mysql   | 2019-03-16T18:15:45.238178Z 0 [ERROR] Aborting
mojipic-mysql   |
```

**Comment by suaaa7** [comment]
datastore以下のファイルを削除したところ、成功

**Comment by suaaa7** [comment]
`Apply this script`が表示され、テーブルが作成されたところまで確認
```
[info] application - Creating Pool for datasource 'default'
[info] p.a.d.DefaultDBApi - Database [default] connected at jdbc:mysql://192.168.99.100:3306/mojipic
[error] application -

! @7b8cohk85 - Internal server error, for (GET) [/] ->

play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
        at play.api.db.evolutions.ApplicationEvolutions.$anonfun$runEvolutions$1(ApplicationEvolutions.scala:78)
        at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:100)
        at play.api.db.evolutions.ApplicationEvolutions.runEvolutions(ApplicationEvolutions.scala:49)
        at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$1(ApplicationEvolutions.scala:42)
        at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$1$adapted(ApplicationEvolutions.scala:42)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:42)
        at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:151)
        at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:50)
        at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:49)
[info] application - Shutting down connection pool.
[info] application - Creating Pool for datasource 'default'
[info] p.a.d.DefaultDBApi - Database [default] connected at jdbc:mysql://192.168.99.100:3306/mojipic
[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter

[info] play.api.Play - Application started (Dev)
```

```
mysql> use mojipic
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables
    -> ;
+--------------------+
| Tables_in_mojipic  |
+--------------------+
| picture_properties |
| play_evolutions    |
+--------------------+
2 rows in set (0.00 sec)
```

**Comment by suaaa7** [comment]
f3f9956
